cluster_name="km-demo-eks-9"
project_name="defaultproject"
blueprint="default"
blueprint_version = "1.17.0"
cloud_credential="km-role"
aws_region="us-west-2"
k8s_version="1.20"
instance_type="t3.xlarge"
